module.exports = {
    exchanges: [
        'kraken.com',
        'poloniex.com',
        'bittrex.com',
        'bitfinex.com',
        'shapeshift.io',
        'chbtc.com',
        'liqui.io',
        'hitbtc.com'
    ],
    supportedCurrencies: [
        'BTC',
        'ETH',
        'BCH',
        'NXT',
        'ETC',
        'LTC',
        'XMR',
        'NMR',
        'ZEC',
        'FCT',
        'DCR',
        'AMP',
        'NAV',
        'BURST',
        'VTC',
        'RADS',
        'DGB',
        'GNT',
        'DGD',
        'BTS',
        'LSK',
        'PPC',
        'DOGE',
        'WAVES',
        'MAID',
        'ARDR',
        'STEEM',
        'DASH',
        'XRP',
        'GNO',
        'TRST',
        'ZEC',
        'SC',
        'POT',
        'SNGLS',
        'CLAM',
        'GUP',
        'BNT',
        'LBC',
        'NMC',
        'DGB',
        'MLN',
        'GRC',
        'ICN',
        'REP',
        'EOS',
        'OMG',
        '1ST',
        'ANT',
        'XEM',
        'LSK',

    ],
    feedInterval: 15000, // How often to update prices (not chain prices), websockets, etc.
    base: 'BTC',
    convertTo: 'ETH', // Can be set to false
    apiEnabled: true,
    redisEnabled: false,
    web3Settings: {
        provider: 'http://localhost:8545',
        testRPC: true,
        gasLimit: 2000000
    },
    priceDiffBuffer: 5, // 10 Percent
    minimumDataPoints: 1, // Anything lower will stop updating on chain prices
    liteMode: true, // Only pushes last prices to chain
    floatPercision: 1000000, // Solidity hates floats, this should be noted for anyone using the oracle
    chainPushInterval: 300000 // How often should we push price data to the chain
}